import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { X, Package, Download, FileText, Check } from 'lucide-react';

const ExportModal = ({ resource, onClose }) => {
  const [copied, setCopied] = useState(false);

  const generateExportContent = () => {
    const lines = [];
    
    lines.push('='.repeat(60));
    lines.push(`STUDY PACK: ${resource.title.toUpperCase()}`);
    lines.push('='.repeat(60));
    lines.push('');
    
    lines.push('DOCUMENT INFO');
    lines.push('-'.repeat(40));
    lines.push(`Category: ${resource.category}`);
    lines.push(`Filename: ${resource.fileName}`);
    lines.push(`Uploaded: ${new Date(resource.uploadedAt).toLocaleDateString()}`);
    lines.push('');
    
    if (resource.analysis) {
      lines.push('AI ANALYSIS');
      lines.push('-'.repeat(40));
      lines.push(resource.analysis);
      lines.push('');
    }
    
    if (resource.keyConcepts?.length > 0) {
      lines.push('KEY CONCEPTS');
      lines.push('-'.repeat(40));
      resource.keyConcepts.forEach((concept, i) => {
        lines.push(`${i + 1}. ${concept}`);
      });
      lines.push('');
    }
    
    if (resource.knowledgeGaps?.length > 0) {
      lines.push('KNOWLEDGE GAPS TO ADDRESS');
      lines.push('-'.repeat(40));
      resource.knowledgeGaps.forEach((gap, i) => {
        lines.push(`${i + 1}. ${gap}`);
      });
      lines.push('');
    }
    
    if (resource.difficultyData) {
      lines.push('DIFFICULTY ANALYSIS');
      lines.push('-'.repeat(40));
      lines.push(`Overall: ${resource.difficultyData.overallLabel} (${resource.difficultyData.overallScore}/10)`);
      lines.push(`Estimated Study Hours: ${resource.difficultyData.estimatedStudyHours}`);
      lines.push(`Summary: ${resource.difficultyData.summary}`);
      if (resource.difficultyData.sections?.length > 0) {
        lines.push('');
        lines.push('Section Breakdown:');
        resource.difficultyData.sections.forEach(section => {
          lines.push(`  - ${section.topic}: ${section.label} (${section.difficulty}/10)`);
          lines.push(`    Tip: ${section.tip}`);
        });
      }
      lines.push('');
    }
    
    lines.push('STUDY PROGRESS');
    lines.push('-'.repeat(40));
    const progress = resource.studyProgress || { flashcardsReviewed: [], conceptsReviewed: [], totalStudyMinutes: 0 };
    lines.push(`Concepts Mastered: ${progress.conceptsReviewed?.length || 0}`);
    lines.push(`Flashcards Reviewed: ${progress.flashcardsReviewed?.length || 0}`);
    lines.push(`Total Study Time: ${Math.floor((progress.totalStudyMinutes || 0) / 60)}h ${(progress.totalStudyMinutes || 0) % 60}m`);
    lines.push('');
    
    if (resource.quizProgress?.totalAttempts > 0) {
      lines.push('QUIZ PERFORMANCE');
      lines.push('-'.repeat(40));
      lines.push(`Attempts: ${resource.quizProgress.totalAttempts}`);
      lines.push(`Best Score: ${resource.quizProgress.bestScore}%`);
      lines.push('');
    }
    
    lines.push('='.repeat(60));
    lines.push('Generated by EduFlow - Smart Study Assistant');
    lines.push('='.repeat(60));
    
    return lines.join('\n');
  };

  const content = generateExportContent();

  const downloadFile = () => {
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${resource.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}-study-pack.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
      className="fixed inset-0 bg-black/60 z-50 flex items-center justify-center p-4"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} exit={{ scale: 0.9, opacity: 0 }}
        className="notion-card max-w-2xl w-full max-h-[90vh] overflow-hidden flex flex-col"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="flex justify-between items-center mb-4">
          <div className="flex items-center gap-2">
            <Package size={20} style={{ color: 'var(--accent)' }} />
            <h3 className="font-heading text-xl">Export Study Pack</h3>
          </div>
          <button onClick={onClose} style={{ color: 'var(--text-muted)' }}>
            <X size={20} />
          </button>
        </div>

        {/* Preview */}
        <div className="flex-1 overflow-hidden flex flex-col min-h-0">
          <p className="text-sm mb-2" style={{ color: 'var(--text-muted)' }}>Preview:</p>
          <pre 
            className="flex-1 overflow-y-auto p-4 rounded-lg text-sm font-mono"
            style={{ background: 'var(--surface-hover)', color: 'var(--text-secondary)' }}
          >
            {content}
          </pre>
        </div>

        {/* Actions */}
        <div className="flex gap-3 mt-4 pt-4 border-t" style={{ borderColor: 'var(--border)' }}>
          <button onClick={downloadFile} className="notion-button flex-1">
            <Download size={16} /> Download .txt
          </button>
          <button onClick={copyToClipboard} className="notion-small-button">
            {copied ? <Check size={16} /> : <FileText size={16} />}
            {copied ? 'Copied!' : 'Copy'}
          </button>
        </div>
      </motion.div>
    </motion.div>
  );
};

export default ExportModal;
